### ISSUE TITLE
Extend IO::Socket::IP to replace ::INET [rt.cpan.org #91699]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Daemon#24]
Migrated from [rt.cpan.org#91699](https://rt.cpan.org/Ticket/Display.html?id=91699) (status was 'open')

Requestors:
* MARKOV@cpan.org

Attachments:
* [0001-Add-IPv6-support.patch](https://rt.cpan.org/Ticket/Attachment/1698920/912376/0001-Add-IPv6-support.patch)
* [0001-Add-IPv6-support.patch](https://rt.cpan.org/Ticket/Attachment/1699040/912443/0001-Add-IPv6-support.patch)
* [HTTP-Daemon-6.01-Handle-undef-and-empty-LocalAddr.patch](https://rt.cpan.org/Ticket/Attachment/1748916/940762/HTTP-Daemon-6.01-Handle-undef-and-empty-LocalAddr.patch)
* [HTTP-Daemon-6.01-Handle-undef-and-empty-LocalAddr.patch](https://rt.cpan.org/Ticket/Attachment/1748919/940767/HTTP-Daemon-6.01-Handle-undef-and-empty-LocalAddr.patch)

From markov@cpan.org on 2013-12-28 01:38:25
:
```
The HTTP::Daemon::ClientConn is based on a IO::Socket::INET object, which is a pity because that does not support IPv6.  The ::IP implementation is a drop-in replacement.
```

From ppisar@redhat.com on 2017-01-16 16:49:48
:
```
Dne PÃ¡ 27.pro.2013 20:38:25, MARKOV napsal(a):
> The HTTP::Daemon::ClientConn is based on a IO::Socket::INET object,
> which is a pity because that does not support IPv6.  The ::IP
> implementation is a drop-in replacement.

Attached patch implements it. Thus is should also fix CPAN RT #71395.

```

From ppisar@redhat.com on 2017-01-17 14:06:39
:
```
Dne Po 16.led.2017 11:49:48, ppisar napsal(a):
> Attached patch implements it. Thus is should also fix CPAN RT #71395.

This patch replaces the previous one. It fixes bad inet_ntop() invocation.

```

From ppisar@redhat.com on 2017-09-18 14:01:01
:
```
Dne Ãt 17.led.2017 09:06:39, ppisar napsal(a):
> Dne Po 16.led.2017 11:49:48, ppisar napsal(a):
> > Attached patch implements it. Thus is should also fix CPAN RT #71395.
> 
> This patch replaces the previous one. It fixes bad inet_ntop() invocation.

Attached patch adds a special handling for undefined and emptry LocalAddr arguments to work around IO::Socket::IP incompatibility (CPAN RT#123069).

```

From ppisar@redhat.com on 2017-09-18 14:27:38
:
```
Dne Po 18.zÃ¡Å.2017 10:01:01, ppisar napsal(a):
> Attached patch adds a special handling for undefined and emptry
> LocalAddr arguments to work around IO::Socket::IP incompatibility
> (CPAN RT#123069).

Grr. I made a typo. Attached patch replaces it.



```

From ppisar@redhat.com on 2018-05-23 15:16:43
:
```
Dne Po 18.zÃ¡Å.2017 10:27:38, ppisar napsal(a):
> Dne Po 18.zÃ¡Å.2017 10:01:01, ppisar napsal(a):
> > Attached patch adds a special handling for undefined and emptry
> > LocalAddr arguments to work around IO::Socket::IP incompatibility
> > (CPAN RT#123069).
> 
> Grr. I made a typo. Attached patch replaces it.
> 
There was another bug found, CPAN RT#125242.



```

**Comment by intrigeri** [comment]
Here's a version of the first patch, updated to apply on top of 6.04: https://salsa.debian.org/perl-team/modules/packages/libhttp-daemon-perl/blob/master/debian/patches/0001-Add-IPv6-support.patch. Since we had the previous version of the patch in Debian's 6.01 package, I've dared applying this refreshed version when updating the package to 6.04. But that's not sustainable on the long term so it would be sweet to have this fixed upstream :)

**Comment by genio** [comment]
That patch looks good, @intrigeri and @ppisar 

I can pull in the patch from that link, or you can submit it as a pull request here and we'll work to get a release cut.

**Comment by intrigeri** [comment]
> I can pull in the patch from that link

Please do :)

**Comment by ppisar** [comment]
I compared the Debian patch a patch I use in Fedora [https://src.fedoraproject.org/rpms/perl-HTTP-Daemon/raw/master/f/HTTP-Daemon-6.04-Add-IPv6-support.patch]. They are the same except mine also corrects t/local/http.t to use Socket instead of IO::Socket.

I believe the reason I chose so is that lib/HTTP/Daemon.pm does not use IO::Socket anymore. But I cannot recall clearly after the long time.

**Comment by genio** [comment]
A release was cut today with the updates: https://metacpan.org/release/ETHER/HTTP-Daemon-6.05  Thanks, everyone!
