### ISSUE TITLE
HTTP::Daemon 6.02 creates a circular dependency with LWP::UserAgent making installation impossible

### ISSUE THREAD

**Issue by noobingitup** [libwww-perl/HTTP-Daemon#26]
When trying to cpan HTTP::Daemon, it requires LWP::UserAgent and vice versa, so unless you already had LWP::UserAgent installed beforehand, installing becomes extremely difficult.

**Comment by oalders** [comment]
Oops!  Looks like `Dist::Zilla` helpfully added `LWP::UserAgent` to the test requirements.  https://metacpan.org/diff/file?source=GAAS/HTTP-Daemon-6.01&target=OALDERS/HTTP-Daemon-6.02#Makefile.PL

Thanks for reporting this.
