### ISSUE TITLE
Two enhancement requests

### ISSUE THREAD

**Issue by terapackets** [libwww-perl/HTTP-Daemon#34]
Thanks for creating HTTP::Daemon.  I have been using it in my projects. 

Recently I found the need for two features I wonder if they are available.

- Can the Daemon (as sockets) work with other plain TCP socket (IO::Socket::INET) via IO::Select? In another word, I want the daemon to act both as HTTP server and regular TCP server at the same time
- Can I have websocket functionality on it?

Thanks in advance,

**Comment by skaji** [comment]
* HTTP::Daemon is just a subclass of IO::Socket::IP, so you can manually use it with select() if you really want to do that.
* I recommend you using other modules for websockets. There are a number of websocket modules on CPAN.

**Comment by terapackets** [comment]
Thanks @skaji for the answer. I tried select() and it works well!

On the websocket, I did see a few modules such as "AnyEvent::WebSocket::Server", "Protocol::WebSocket",   "Net::WebSocket::Server", but they don't seem to fit in HTTP::Daemon.
Any suggestions?  Thanks.

**Comment by skaji** [comment]
For websockets, I mean "Don't use HTTP::Daemon at all. Instead, use other CPAN modules".

**Comment by genio** [comment]
Agreed. Mojolicious is your friend here.

**Comment by terapackets** [comment]
Thank you @skaji @genio !  Mojo is the way to go!
