### ISSUE TITLE
"cpanm --verbose --no-interactive --reinstall HTTP::Daemon" fails in travis-ci / bionic / system /usr/bin/perl

### ISSUE THREAD

**Issue by shlomif** [libwww-perl/HTTP-Daemon#39]
`cpanm --verbose --no-interactive --reinstall HTTP::Daemon` fails when running in travis-ci:

* https://travis-ci.org/github/shlomif/quad-pres/builds/685709162 (note the branch)

* https://github.com/shlomif/quad-pres/tree/travis-cpan-install-HTTP-Daemon--test ( note the branch)

Some of the tests appear to be stalling. I am on the default "language: ruby" with the default perl.

**Comment by oalders** [comment]
Are you able to pinpoint the release where this starts to happen?

**Comment by shlomif** [comment]
@oalders :  see the build history at https://travis-ci.org/github/shlomif/quad-pres/builds - builds started failing 13 days ago, but there was a commit gap from the previous commits which were 4 months before today (= 11 May 2020).

**Comment by oalders** [comment]
@shlomif if you could re-run the build with and target installing 6.05 as well as 6.04, I'd be interested to see if you get the same result.

**Comment by shlomif** [comment]
@oalders : see https://travis-ci.org/github/shlomif/quad-pres/builds/685725078 - thanks!

**Comment by shlomif** [comment]
@oalders : v6.04 at https://travis-ci.org/github/shlomif/quad-pres/builds/685733178

**Comment by oalders** [comment]
@shlomif thank you. That's helpful.  I wonder if this is related to #37

**Comment by jkeenan** [comment]
> @shlomif thank you. That's helpful. I wonder if this is related to #37

... which in turn raises the question of whether it will be fixed by the application of the p.r. in https://github.com/libwww-perl/HTTP-Daemon/pull/40.

**Comment by oalders** [comment]
@shlomif does the problem persist with https://metacpan.org/release/OALDERS/HTTP-Daemon-6.07-TRIAL ?

**Comment by shlomif** [comment]
@oalders : thanks! Trying at https://travis-ci.org/github/shlomif/quad-pres/builds/689107853 (note the branch).

**Comment by shlomif** [comment]
@oalders : it failed: https://travis-ci.org/github/shlomif/quad-pres/builds/689107853 :(

**Comment by jkeenan** [comment]
> @oalders : it failed: https://travis-ci.org/github/shlomif/quad-pres/builds/689107853 :(

Does this error appear if you try to build this outside of the travis environment?

**Comment by shlomif** [comment]
> > @oalders : it failed: https://travis-ci.org/github/shlomif/quad-pres/builds/689107853 :(
> 
> Does this error appear if you try to build this outside of the travis environment?

@jkeenan : on my local fedora 32 x86-64 system the command `cpanm --verbose --no-interactive --reinstall 'https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.07-TRIAL.tar.gz'` is successful (after enabling local-lib). I also recall trying `cpanm HTTP::Daemon` on ubuntu VMs where it also was successful. Note that if necessary one can detect if the problem tests are running on travis using `$ENV{TRAVIS} eq "true"` and skip them: https://docs.travis-ci.com/user/environment-variables/ .

**Comment by oalders** [comment]
@shlomif does this work on Travis with https://metacpan.org/release/OALDERS/HTTP-Daemon-6.08-TRIAL ?

**Comment by shlomif** [comment]
> @shlomif does this work on Travis with https://metacpan.org/release/OALDERS/HTTP-Daemon-6.08-TRIAL ?

Seems to work fine there: https://travis-ci.org/github/shlomif/quad-pres/builds/690146037 (note the branch) - thanks for the fix!

**Comment by oalders** [comment]
Excellent.  Thanks @shlomif!
