### ISSUE TITLE
Could not connect to '[::1]:13381': IO::Socket::INET: Bad hostname '[::1]'

### ISSUE THREAD

**Issue by DrHyde** [libwww-perl/HTTP-Daemon#49]
The tests for HTTP-Daemon-6.12 hang in t/url.t when using perl 5.20.2 on FreeBSD 13 thus:

```
$ .../perl-5.20.2/bin/perl -Mblib t/url.t
# url: http://[::1]:13381/
# 599 Internal Exception
# Could not connect to '[::1]:13381': IO::Socket::INET: Bad hostname '[::1]'
```

They pass on the same machine using perl 5.32.0, so I **ass**ume that there's a dependency on a higher version of some module that comes with 5.20.2 where you've not given the right version number.

**Comment by oalders** [comment]
Thanks @DrHyde! Which versions of `IO::Socket::IP` are on 5.32.0 and 5.20.2?

**Comment by DrHyde** [comment]
```
$ corelist -a IO::Socket::IP |grep -E 5.\(32.0\|20.2\)
  v5.20.2    0.29
  v5.32.0    0.39
```

I can confirm that upgrading it to the latest from the CPAN (0.41) fixes things, but if you'd like me to bisect and find the earliest version that makes it work I can do that.

**Comment by DrHyde** [comment]
Well that didn't take long. IO::Socket::IP 0.32 seems to be sufficient.

**Comment by oalders** [comment]
Wonderful -- thanks @DrHyde!

**Comment by DrHyde** [comment]
Looking at the changelog for IO::Socket::IP I can't see any mention of this for that version, so I expect it was fixed by mistake! Calling @leonerd!
