### ISSUE TITLE
HTTP::Daemon has undeclared dependencies

### ISSUE THREAD

**Issue by jkeenan** [libwww-perl/HTTP-Daemon#55]
Today I attempted to install Test::Smoke against Perl 5 blead using `cpan` as the installer.  The `cpan` utility detected two undeclared dependencies in HTTP::Daemon.
```
Running test for module 'HTTP::Daemon'
Fetching with HTTP::Tiny:
https://cpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.14.tar.gz
Checksum for /home/jkeenan/.cpan/sources/authors/id/O/OA/OALDERS/HTTP-Daemon-6.14.tar.gz ok
---- Unsatisfied dependencies detected during ----
----      OALDERS/HTTP-Daemon-6.14.tar.gz     ----
    Module::Build::Tiny [build_requires]
Running test for module 'Module::Build::Tiny'
Checksum for /home/jkeenan/.cpan/sources/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz ok
  Warning: CPAN.pm discovered Module::Build as undeclared prerequisite.
  Adding it now as such.
---- Unsatisfied dependencies detected during ----
----   LEONT/Module-Build-Tiny-0.039.tar.gz   ----
    ExtUtils::Config [build_requires]
    ExtUtils::Helpers [build_requires]
    ExtUtils::InstallPaths [build_requires]
    Module::Build [build_requires]
Running test for module 'ExtUtils::Config'
```
Module-Build and Module-Build-Tiny were reported as unsatisfied.  Can you investigate?

**Comment by skaji** [comment]
So did you fail to install HTTP::Daemon?

**Comment by jkeenan** [comment]
On 4/1/22 18:53, Shoichi Kaji wrote:
> So did you fail to install HTTP::Daemon?
> 

No, `cpan` is smart enough to add the two undeclared dependencies and 
install them.  I'm merely calling the lack of declaration to your attention.

**Comment by skaji** [comment]
https://metacpan.org/release/OALDERS/HTTP-Daemon-6.14/source/META.json#L26
HTTP::Daemon requires Module::Build::Tiny,
and cpan.pm correctly detected it and tries to install it.
I don't see anything wrong.

Module::Build is not related to HTTP::Daemon, directly.

**Comment by skaji** [comment]
> Warning: CPAN.pm discovered Module::Build as undeclared prerequisite.

This is an issue of cpan.pm, I guess,

**Comment by karenetheridge** [comment]
@jkeenan do you have an old CPAN.pm? see the big block of text in Build.PL that calls to your attention an old toolchain.

**Comment by jkeenan** [comment]
On 4/1/22 19:33, Karen Etheridge wrote:
> @jkeenan <https://github.com/jkeenan> do you have an old CPAN.pm? see 
> the big block of text in Build.PL that calls to your attention an old 
> toolchain.
> 

$ ./bin/cpan -V | head -n 2 | tail -n 1
 >(info): ./bin/cpan script version 1.678, CPAN.pm version 2.33

**Comment by skaji** [comment]
* HTTP::Daemon requires Module::Build::Tiny https://metacpan.org/release/OALDERS/HTTP-Daemon-6.14/source/META.json#L26
* CPAN.pm adds Module::Build as a dependency, which is not really necessary and will be fixed by 
https://github.com/andk/cpanpm/pull/136
